### ISSUE TITLE
Encode integers as varint

### ISSUE THREAD

**Issue by medisoft** [sitegui/js-binary#3]
It could be good for space allocation to use varint to encode integers, or at least to have a type of varint.

**Comment by sitegui** [comment]
Hi @medisoft 

int and uint are already represented with varying number of bytes (1, 2, 4 or 8)

For uint, values from 0 to 127 are stored in 1 byte, 128 to 16383 in 2 bytes, ...
[see relevant code](https://github.com/sitegui/js-binary/blob/master/lib/types.js#L23)

Some bits are used to store how many bytes are used, so there's some waste there.
Do you have any suggestions on improving this?
